# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af060f9da007453508ba8d8988caac7f5cbbf8db3ef2e71744c0f5ce1bee833b5428c04544732e52bf3ac223b51b09f94c4a6999015cec6061fb32c6837e8825

test:
  secret_key_base: 639171d470984dd9d2e6adf64c9216b7c369f5a2617e289687b361aa3f3efc8d1b03ff12f7c6e16785e99c4eaafede977b0be99f6c4728446b0c74432e24478e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
